# GitHub Sponsors, Paypal, and UPI configuration for donation
# This file enables the "Sponsor" button on your GitHub repository.

# Enable custom links
custom: [
  "https://ko-fi.com/nextlief",
  "https://kfcc876.github.io/nextlief/support"
]
